name: Test

on:
#  schedule:
#    - cron: "22 */4 * * *"
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04 
    steps:
      - run: uname -a && dpkg --print-architecture
      - name: Checkout
        uses: actions/checkout@v5
      - name: Run tests
        run: python src/commands.cob
